apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kgh0lxn0v-go
  janus-idp.io/tekton: kgh0lxn0v-go
  backstage.io/kubernetes-id: kgh0lxn0v-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kgh0lxn0v-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
